### ISSUE TITLE
Could not load two-factor auth provider

### ISSUE THREAD

**Issue by eniac111** [ChristophWurst/twofactor_sms#6]
Hello,

I'm getting this error: 

`{"reqId":"FopShCwj6uK5IK8FPhfs","remoteAddr":"10.244.250.1","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Could not load two-factor auth provider OCA\\\\TwoFactor_Sms\\\\Provider\\\\SmsProvider\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php(67): OC\\\\Authentication\\\\TwoFactorAuth\\\\Manager->getProviders(Object(OC\\\\User\\\\User))\\n#1 \\\/var\\\/www\\\/owncloud\\\/core\\\/Middleware\\\/TwoFactorMiddleware.php(94): OC\\\\Authentication\\\\TwoFactorAuth\\\\Manager->isTwoFactorAuthenticated(Object(OC\\\\User\\\\User))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(94): OC\\\\Core\\\\Middleware\\\\TwoFactorMiddleware->beforeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(111): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(967): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php\",\"Line\":121}","level":3,"time":"2016-09-15T14:07:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"blago"}
`
..when I put example credentials for websms.de. 

Tested on NextCloud 10 with Apache and Sqlite.

Btw, I have almost working commit with user settings for the phone number.

Regards,
Blagovest Petrov

**Comment by eniac111** [comment]
Excuse me, I understood where is the problem. The API is is changed

**Comment by ChristophWurst** [comment]
> Btw, I have almost working commit with user settings for the phone number.

Hey @eniac111,

what's the status on that? A pull request is very welcome, you can also push your work-in-progress :-)

**Comment by eniac111** [comment]
@ChristophWurst Hi, I wanted to review my code first but ok. I'll push it anyway :)
